import { TrailerCardType } from "../model/type";

export const productBadge = {
  new: { label: "новый", color: "badge.new" },
  used: { label: "с пробегом", color: "badge.used" },
  tradeIn: { label: "trade-in", color: "badge.tradeIn" },
};

export const TRAILER_MOCK: TrailerCardType[] = [
  {
    product_category: "new",
    trailer_category: "Бортовой",
    model: "МЗСА 817701",
    capacity: 950,
    width: 1371,
    length: 2512,
    height: 290,
    price: 185000,
    createdAt: "2024-11-15",
    year: 2024,
    images: [
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
    ],
  },
  {
    product_category: "new",
    trailer_category: "Лодочный",
    model: "МЗСА 81771C",
    capacity: 750,
    width: 1960,
    length: 5200,
    price: 142000,
    createdAt: "2024-10-20",
    year: 2024,
    images: [
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
    ],
  },
  {
    product_category: "used",
    trailer_category: "Бортовой",
    model: "ЛАВ 81012А",
    capacity: 560,
    width: 1230,
    length: 2050,
    height: 400,
    price: 75000,
    createdAt: "2024-08-05",
    year: 2022,
    images: [
      "/images/trailers/trailer-3.jpg",
      "/images/trailers/trailer-3.jpg",
      "/images/trailers/trailer-3.jpg",
      "/images/trailers/trailer-3.jpg",
    ],
  },
  {
    product_category: "new",
    trailer_category: "Самосвальный",
    model: "МЗСА 900101",
    capacity: 1200,
    width: 1510,
    length: 2700,
    height: 350,
    price: 230000,
    createdAt: "2025-01-10",
    year: 2025,
    images: [
      "/images/trailers/trailer-4.jpg",
      "/images/trailers/trailer-4.jpg",
      "/images/trailers/trailer-4.jpg",
      "/images/trailers/trailer-4.jpg",
    ],
  },
  {
    product_category: "tradeIn",
    trailer_category: "Автовоз",
    model: "ЧМЗАП 99064",
    capacity: 2500,
    width: 2200,
    length: 6800,
    price: 420000,
    createdAt: "2024-06-18",
    year: 2021,
    images: [
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
      "/images/trailers/trailer-1.jpg",
    ],
  },
  {
    product_category: "new",
    trailer_category: "Фургон",
    model: "МЗСА 817773",
    capacity: 800,
    width: 1371,
    length: 2512,
    height: 1520,
    price: 265000,
    createdAt: "2025-02-01",
    year: 2025,
    images: [
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
      "/images/trailers/trailer-2.jpg",
    ],
  },
];
