import { CarCardType } from "../model/type";

export const carBadge = {
  new: { label: "новый", color: "badge.new" },
  used: { label: "с пробегом", color: "badge.used" },
  tradeIn: { label: "trade-in", color: "badge.tradeIn" },
};

export const CAR_MOCK: CarCardType[] = [
  {
    brand: "BMW",
    model: "5 Series",
    year: 2021,
    engineVolume: 2.0,
    mileage: 45000,
    price: 4200000,
    transmission: "Автомат",
    power: 184,
    category: "used",
    images: ["/images/cars/bmw-1.jpeg", "/images/cars/bmw-2.jpeg", "/images/cars/bmw-3.jpeg"],
    createdAt: "2024-02-10",
  },
  {
    brand: "Kia",
    model: "K5",
    year: 2022,
    engineVolume: 1.6,
    mileage: 30000,
    price: 2100000,
    transmission: "Робот",
    power: 180,
    category: "tradeIn",
    images: ["/images/cars/kia-1.jpg", "/images/cars/kia-2.webp", "/images/cars/kia-3.jpg"],
    createdAt: "2024-03-05",
  },
  {
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2023,
    engineVolume: 2.0,
    mileage: 5000,
    price: 6500000,
    transmission: "Автомат",
    power: 197,
    category: "new",
    images: [
      "/images/cars/merc-1.jpeg",
      "/images/cars/merc-2.webp",
      "/images/cars/merc-3.jpg",
    ],
    createdAt: "2024-03-20",
  },
  {
    brand: "Hyundai",
    model: "Sonata",
    year: 2020,
    engineVolume: 2.0,
    mileage: 68000,
    price: 1750000,
    transmission: "Автомат",
    power: 150,
    category: "used",
    images: [
      "/images/cars/sonata-1.webp",
      "/images/cars/sonata-2.jpg",
      "/images/cars/sonata-3.jpg",
    ],
    createdAt: "2024-01-28",
  },
];
